default_config:

logger:
  default: info
  logs:
    custom_components.average: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

sensor:
  - platform: template
    sensors:
      test1:
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
        unit_of_measurement: '°C'
        device_class: 'temperature'
      test2:
        value_template: "{{ 2 }}"
        unit_of_measurement: '°C'
        device_class: 'temperature'

  - platform: average
    entities:
      - sensor.test1
      - sensor.test2
