name: HACS

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    name: HACS
    steps:
      - uses: "actions/checkout@v2"
      - if: github.repository != 'Limych/ha-blueprint'
        name: HACS validation
        uses: "hacs/action@main"
        with:
          CATEGORY: "integration"
